# Site settings
title: Blog of hxg_
header-img: img/post-bg-01.jpg
email: hexige408@gmail.com
copyright_name: yunlaiwu
description: "just desc"
baseurl: "/blog"
url: "http://hexige.github.io"
email_username:  hexige@yunlaiwu.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

gems: [jekyll-paginate, jekyll-feed]
theme: jekyll-theme-hacker